-- Migration: 20260505_01_create_refund_requests_table.sql
--
-- Creates the refund_requests table so that buyer return requests are
-- persisted in the database before emails are sent. Previously,
-- submitRefundRequestAction only sent emails — if Resend was unavailable or
-- the email was missed, the request was permanently lost with no portal record.
--
-- Design decisions:
--   • Reference number auto-generated by a BEFORE INSERT trigger: RRQ-00001.
--   • status enum: pending → acknowledged → resolved (admin workflow).
--   • profile_id is denormalized (can be derived from orders.profile_id) for
--     fast single-table buyer-scoped queries without a join.
--   • acknowledged_by / resolved_by capture which admin actioned each step.
--   • RLS: buyers read their own records. Writes go through service_role only
--     (adminClient, rolbypassrls = true — never from the browser).
--   • FORCE RLS: consistent with all other tables (20260504_02_phase2_hardening).
--   • Audit trigger: consistent with all other tables (20260414_08_L11).
--
-- ─────────────────────────────────────────────────────────────────────────────
-- PRE-FLIGHT CHECKS
-- Run in the SQL Editor BEFORE applying this migration. Expected results noted.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- 1. Confirm table does not already exist (expected: 0 rows):
--
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_name = 'refund_requests';
--
-- 2. Confirm sequence does not already exist (expected: 0 rows):
--
-- SELECT sequence_name FROM information_schema.sequences
-- WHERE sequence_schema = 'public'
--   AND sequence_name = 'refund_request_reference_seq';
--
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Sequence for auto-generated reference numbers (RRQ-00001, RRQ-00002, ...)
CREATE SEQUENCE IF NOT EXISTS public.refund_request_reference_seq START 1;

-- 2. Table
CREATE TABLE IF NOT EXISTS public.refund_requests (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  reference        TEXT        NOT NULL UNIQUE,
  order_id         UUID        NOT NULL REFERENCES public.orders(id)   ON DELETE RESTRICT,
  profile_id       UUID        NOT NULL REFERENCES public.profiles(id)  ON DELETE RESTRICT,
  reason           TEXT        NOT NULL
    CHECK (reason IN ('defective_damaged', 'incorrect_items', 'not_as_described', 'other')),
  date_received    TEXT        NOT NULL,
  details          TEXT,
  status           TEXT        NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'acknowledged', 'resolved')),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  acknowledged_at  TIMESTAMPTZ,
  acknowledged_by  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  resolved_at      TIMESTAMPTZ,
  resolved_by      UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  resolution_notes TEXT
);

COMMENT ON TABLE public.refund_requests IS
  'Buyer return/refund requests persisted before email dispatch. Reference auto-generated (RRQ-NNNNN). Admin workflow: pending → acknowledged → resolved.';

COMMENT ON COLUMN public.refund_requests.reference IS
  'Human-readable reference auto-assigned by trg_refund_requests_reference trigger. Format: RRQ-NNNNN.';
COMMENT ON COLUMN public.refund_requests.profile_id IS
  'Denormalized buyer ID. Matches orders.profile_id for the referenced order. Enables single-table buyer-scoped queries.';
COMMENT ON COLUMN public.refund_requests.date_received IS
  'Date buyer reports receiving the goods (freeform text, validated as a date by the application layer).';

-- 3. Auto-generate reference on INSERT via trigger
CREATE OR REPLACE FUNCTION public.generate_refund_reference()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.reference := 'RRQ-' || LPAD(nextval('refund_request_reference_seq')::text, 5, '0');
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_refund_requests_reference
  BEFORE INSERT ON public.refund_requests
  FOR EACH ROW EXECUTE FUNCTION public.generate_refund_reference();

-- 4. Indexes
CREATE INDEX IF NOT EXISTS idx_refund_requests_order_id
  ON public.refund_requests (order_id);

CREATE INDEX IF NOT EXISTS idx_refund_requests_profile_id
  ON public.refund_requests (profile_id);

CREATE INDEX IF NOT EXISTS idx_refund_requests_status
  ON public.refund_requests (status);

CREATE INDEX IF NOT EXISTS idx_refund_requests_created_at
  ON public.refund_requests (created_at DESC);

-- 5. Enable RLS + FORCE RLS
ALTER TABLE public.refund_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refund_requests FORCE ROW LEVEL SECURITY;

-- 6. RLS policies
--    service_role (adminClient, rolbypassrls = true) bypasses all policies.
--    Authenticated buyers may SELECT their own records only.
--    All writes go through service_role — no direct INSERT/UPDATE/DELETE
--    from the authenticated or anon roles.
DROP POLICY IF EXISTS "buyers_read_own_refund_requests" ON public.refund_requests;
CREATE POLICY "buyers_read_own_refund_requests"
  ON public.refund_requests
  FOR SELECT
  TO authenticated
  USING (profile_id = auth.uid());

REVOKE INSERT, UPDATE, DELETE ON public.refund_requests FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.refund_requests FROM anon;

-- 7. Audit trigger (same pattern as all other tables)
CREATE TRIGGER trg_audit_refund_requests
  AFTER INSERT OR UPDATE OR DELETE ON public.refund_requests
  FOR EACH ROW EXECUTE FUNCTION public.log_table_audit();

-- ─────────────────────────────────────────────────────────────────────────────
-- POST-FLIGHT VERIFICATION QUERIES
-- Run in the SQL Editor immediately after applying. Expected results noted.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- 1. Confirm all columns exist:
--
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'refund_requests'
-- ORDER BY ordinal_position;
-- Expected: 14 rows (id, reference, order_id, profile_id, reason, date_received,
--           details, status, created_at, acknowledged_at, acknowledged_by,
--           resolved_at, resolved_by, resolution_notes)
--
-- 2. Confirm RLS enabled and forced (expect both = true):
--
-- SELECT relname, relrowsecurity, relforcerowsecurity
-- FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
-- WHERE n.nspname = 'public' AND c.relname = 'refund_requests';
--
-- 3. Confirm triggers (expect 2 triggers):
--
-- SELECT trigger_name, event_manipulation, action_timing
-- FROM information_schema.triggers
-- WHERE event_object_table = 'refund_requests'
-- ORDER BY trigger_name;
-- Expected:
--   trg_audit_refund_requests  — AFTER  INSERT/UPDATE/DELETE
--   trg_refund_requests_reference — BEFORE INSERT
--
-- 4. Confirm RLS policies (expect 1 policy):
--
-- SELECT policyname, cmd, roles
-- FROM pg_policies
-- WHERE tablename = 'refund_requests';
-- Expected: buyers_read_own_refund_requests (SELECT, authenticated)
--
-- 5. Test reference generation (run in a transaction and roll back):
--
-- BEGIN;
-- INSERT INTO public.refund_requests
--   (order_id, profile_id, reason, date_received)
-- VALUES
--   ('00000000-0000-0000-0000-000000000001',
--    '00000000-0000-0000-0000-000000000001',
--    'other', '2026-05-05')
-- RETURNING reference;
-- -- Expected: RRQ-00001 (or next in sequence)
-- ROLLBACK;
--
-- ─────────────────────────────────────────────────────────────────────────────
-- ROLLBACK SQL
-- Apply in the SQL Editor if this migration needs to be reverted.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- DROP TRIGGER IF EXISTS trg_audit_refund_requests    ON public.refund_requests;
-- DROP TRIGGER IF EXISTS trg_refund_requests_reference ON public.refund_requests;
-- DROP FUNCTION IF EXISTS public.generate_refund_reference();
-- DROP TABLE  IF EXISTS public.refund_requests;
-- DROP SEQUENCE IF EXISTS public.refund_request_reference_seq;
